require 'mockdata/animals'
require 'mockdata/avatars'
require 'mockdata/locations'
require 'mockdata/names'
require 'mockdata/numbers'
require 'mockdata/people'
require 'mockdata/time_zones'
require "mockdata/version"
require 'mockdata/words'
